version: '2'

services:
  php: 
    build: ./php
    volumes:
      - ./src/myapp:/var/www
    depends_on:
      - mysql
  
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./src/myapp:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
